name: Docker Image CI


on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.22.0
      with:
        # This data can be any valid JSON from a previous step in the GitHub Action
        payload: |
          {
            "CVE_Identifier": "Test-CVE",
            "Image": "Test-Image"
          }
      env:
        SLACK_WEBHOOK_URL: https://hooks.slack.com/workflows/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

